theme = "tokyonight_storm"

[editor]
line-number = "relative"
mouse = false
color-modes = true
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

